const animals={
raccoon:{e:"🦝",name:"RACCOON",tag:"Small. Resourceful. Suspicious.",desc:"You possess the remarkable ability to survive situations entirely of your own creation.",likes:"snacks, friendship, objects",dislikes:"consequences",habitat:"somewhere it shouldn't be"},
frog:{e:"🐸",name:"FROG",tag:"Round. Observant. Damp-adjacent.",desc:"You would survive being placed near a pond. This is apparently a personality trait.",likes:"sitting, vibes, small jumps",dislikes:"being perceived",habitat:"one excellent leaf"},
penguin:{e:"🐧",name:"PENGUIN",tag:"Walks strangely. Surprisingly employable.",desc:"You are loyal, organised-ish, and look like you have somewhere important to be.",likes:"the team, snacks in groups",dislikes:"unnecessary solo missions",habitat:"the group chat"},
dog:{e:"🐕",name:"DOG",tag:"YAYYYYYYYYY.",desc:"You clicked the excited answer too many times. Please settle down. We are trying to conduct science.",likes:"EVERYONE!!! EVERYTHING!!!",dislikes:"when people leave :(",habitat:"wherever the people are"},
duck:{e:"🦆",name:"DUCK",tag:"No explanation. Just duck.",desc:"You chose the questionable option with alarming consistency. The system respects this.",likes:"eating it",dislikes:"follow-up questions",habitat:"yes"},
cat:{e:"🐈",name:"CAT",tag:"Independently operating.",desc:"You participated in this quiz on your own terms and would like that noted in the minutes.",likes:"competence, naps",dislikes:"being summoned",habitat:"nearby but not involved"}
};
const Q=[
{q:"You find a $2 coin on the floor. What do you do?",a:[["Pick it up","frog"],["Leave it","cat"],["Investigate the surrounding area for more coins","raccoon"],["YAYYYYY $2!!!!!!!!","dog"],["Eat it","duck"]]},
{q:"You have been placed in a room.",sub:"There is one chair, a microwave, 47 grapes, and Brian. What do you interact with first?",a:[["🪑 Chair","frog"],["🍇 Grapes","raccoon"],["👋 Brian","dog"],["Why is there no option for the microwave?","cat"]]},
{q:"Choose a defensive manoeuvre.",a:[["🏃 RUN","dog"],["🧍 Stand very still","penguin"],["🪿 Become goose","duck"],["📞 Call Pastor Grace","frog"],["🪑 Chair","raccoon"]]},
{q:"It is Monday.",a:[["😌 Yes","penguin"],["😨 Oh.","raccoon"],["🤨 And?","cat"],["👁️ Why are you asking me this","frog"],["🦆 Eat it","duck"]]},
{q:"You receive a message:",sub:'“hellooo friendly reminder PCRs are due tonight!! 🥰”<br><br>What happens internally?',a:[["A. Peace","penguin"],["B. Conviction","frog"],["C. I did it already 😎","cat"],["D. I will do it after this quiz","dog"],["E. HOW DID THIS BECOME ABOUT PCR","raccoon"]]}
];
let i=-1,scores={},last="",muted=false;const card=document.querySelector("#card"),counter=document.querySelector("#counter");
function bleep(){if(muted)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=280+Math.random()*120;g.gain.value=.025;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.06)}catch(e){}}
function renderStart(){card.innerHTML='<div class="eyebrow">A VERY SERIOUS WEBSITE</div><div class="emoji">🧐</div><h1>WHAT ANIMAL<br>ARE YOU?</h1><p>There are many animals.<br>You are probably one of them.</p><button class="bigbtn" onclick="next()">FIND OUT →</button><div class="tiny">results are legally questionable</div>'}
function next(type){bleep();if(type){scores[type]=(scores[type]||0)+1;last=type}i++;if(i>=Q.length)return calculate();let x=Q[i];counter.textContent='question '+(i+1)+' of '+Q.length;card.innerHTML='<div class="eyebrow">IMPORTANT CLASSIFICATION QUESTION</div><h2>'+x.q+'</h2>'+(x.sub?'<p>'+x.sub+'</p>':'')+'<div class="choices">'+x.a.map((v,n)=>'<button class="choice" onclick="answer(\''+v[1]+'\','+i+','+n+')">'+v[0]+'</button>').join('')+'</div>'}
function answer(type,qi,n){if(qi===1&&n===3){card.innerHTML='<div class="emoji">📡</div><h2>The microwave does not concern you.</h2><p>Do not bring up the microwave again.</p><button class="bigbtn" onclick="next(\''+type+'\')">continue animal quiz</button>';return}if(qi===4&&n===4){scores[type]=(scores[type]||0)+1;card.innerHTML='<div class="warning">⚠️</div><h2>Please remain calm.</h2><p>This is still an animal quiz.</p><button class="bigbtn" onclick="calculate()">continue animal quiz</button>';return}next(type)}
function calculate(){counter.textContent="laboratory processing";card.innerHTML='<div class="emoji">🔬</div><h2 id="calc">Analysing responses...</h2><div class="loader"><span></span></div><p id="status">Measuring animal...</p>';let lines=["Measuring animal...","Consulting zoologist...","Zoologist unavailable.","Consulting guy we found outside...","Checking Monday responsibilities...","Animal located."];let k=0,t=setInterval(()=>{document.querySelector("#status").textContent=lines[k++]||"";if(k===lines.length){clearInterval(t);setTimeout(result,650)}},700)}
function result(){let key=Object.keys(animals).sort((a,b)=>(scores[b]||0)-(scores[a]||0))[0]||last||"duck";let a=animals[key];counter.textContent="classification complete";card.innerHTML='<div class="eyebrow">WE HAVE YOUR RESULT</div><div class="emoji">'+a.e+'</div><h1>YOU ARE A '+a.name+'.</h1><p><b>'+a.tag+'</b><br>'+a.desc+'</p><div class="resultbox"><b>LIKES:</b> '+a.likes+'<br><b>DISLIKES:</b> '+a.dislikes+'<br><b>NATURAL HABITAT:</b> '+a.habitat+'<br><b>PCR STATUS:</b> 👁️ unknown</div><button class="bigbtn" onclick="accept(\''+key+'\')">ACCEPT '+a.name+' →</button>'}
function accept(key){confetti();let a=animals[key];card.innerHTML='<div class="emoji">'+a.e+'🎉</div><h2>Congratulations!</h2><p>Your classification has been submitted to the International Animal Database.*</p><div class="tiny">*There is no International Animal Database.</div><br><button class="bigbtn" onclick="ambush(\''+key+'\')">okay cool what now</button>'}
function ambush(key){let a=animals[key];counter.textContent="one final matter";card.innerHTML='<div class="warning">📋</div><h1>do your PCR.</h1><p>'+a.e+' <b>'+a.name+' HAS ONE FINAL TASK.</b></p><p>PCRs are due by the end of Monday.<br><br>'+a.name[0]+a.name.slice(1).toLowerCase()+' cannot complete your PCR.<br>'+a.name[0]+a.name.slice(1).toLowerCase()+' does not know what pastoral care is.<br>'+a.name[0]+a.name.slice(1).toLowerCase()+' has no access to the form.<br><br><b>You do.</b></p><button class="bigbtn" onclick="finale()">GO DO MY PCR 😔</button>'}
function finale(){confetti();card.innerHTML='<div class="emoji">🫡</div><h1>GO FORTH.</h1><p>Complete the PCR.<br>Restore balance to the universe.<br>Pastoral care depends on you.</p><button class="bigbtn" onclick="location.reload()">take the extremely valid quiz again</button>'}
function confetti(){for(let j=0;j<35;j++){let s=document.createElement("span");s.textContent=["🎉","⭐","🍇","🦆","✨"][j%5];s.style.left=Math.random()*100+"vw";s.style.top="-40px";s.style.animationDelay=Math.random()*.8+"s";document.querySelector("#floaties").appendChild(s);setTimeout(()=>s.remove(),4000)}}
document.querySelector("#sound").onclick=()=>{muted=!muted;document.querySelector("#sound").textContent=muted?"🔇":"🔊"};renderStart();